#!/bin/sh

RC='/opt/etc/init.d/rc.unslung'

i=30
until [ -x "$RC" ] ; do
  i=$(($i-1))
  if [ "$i" -lt 1 ] ; then
    logger "Could not start Entware"
    exit
  fi
  sleep 1
done
$RC start

nohup /jffs/scripts/checknetwork.sh >> /tmp/mnt/sda1/network_state.log 2>&1 &
nohup /jffs/scripts/AdGuardHome.sh >> /tmp/mnt/sda1/ad_script.log 2>&1 &
